#!/bin/bash

# quick script to show when I open a terminal

echo
echo '~~~~~~~~Hey Henry, welcome back.~~~~~~~~~'
echo 
echo 'The time is....'; date
echo
echo 'CPU temps:'; sensors | grep 'temp1'
echo
echo 'Memory usage:'; free -h | grep 'free'; free -h | grep 'Mem'
echo
echo 'Disk space:'; df -h | grep 'Avail'; df -h | grep '/dev/sda1'
echo
echo 'Enjoy!'
echo
echo '########################################'
echo

sleep 1
