#!/bin/bash

echo
echo "~~~apt update~~~"
echo 
echo

apt update

echo
echo "~~~apt upgrade~~~"
echo
echo

apt upgrade

echo 
echo "~~~apt autoremove~~~"
echo 
echo

apt autoremove

echo
echo
echo "Done."
echo
