#!/bin/bash

echo
echo "~~~apt update~~~"
echo 
echo

apt update

echo
echo "~~~apt upgrade~~~"
echo
echo

apt upgrade

echo
echo "~~~aptitude -f install~~~"
echo
echo

aptitude -f install 

echo
echo "~~~aptitude clean~~~"
echo
echo

aptitude clean

echo
echo "~~~aptitude autoclean~~~"
echo
echo

aptitude autoclean

echo
echo
echo "Done."
echo
