#!/bin/bash

echo
echo "~~~aptitude update~~~"
echo 
echo

aptitude update

echo
echo "~~~aptitude upgrade~~~"
echo
echo

aptitude upgrade

echo
echo "~~~aptitude -f install~~~"
echo
echo

aptitude -f install 

echo
echo "~~~aptitude clean~~~"
echo
echo

aptitude clean

echo
echo "~~~aptitude autoclean~~~"
echo
echo

aptitude autoclean

echo
echo
echo "Done."
echo
